### ISSUE TITLE
嵌入式linux CRC32校验值和服务器linux CRC32校验值不一样

### ISSUE THREAD

**Issue by linxingyang** [gityf/crc#1]
(都是中国人哈，就不说外国话了)

同一个串
```
7F 7E 00 00 00 
00 08 00 00 00 
00 04 1D 00 09
```
在嵌入式 (arm 新唐)中
```
# 你的crc32
crc=294be25
# 我另外用的一个库crc32
crc=fd6b41db
```

在服务器(ubuntu 16)中
```
# 你的crc32
crc=fd6b41db
# 我另外用的一个库crc32
crc=fd6b41db
```

哈哈，我还以为源码没问题，卡了我一点时间，最后发现是源码问题

**Comment by jiladahe1997** [comment]
应该是labs()求了绝对值的问题，0x0294be25 和 0xfd6b41db刚好是补码的关系。

crc32.c 第77行。
```
uint32_t crc32(const char* s, int len)
{
    int i;
    uint32_t crc32val = 0;
    crc32val ^= 0xFFFFFFFF;

    for (i = 0;  i < len;  i++) {
        crc32val = crc32_tab[(crc32val ^ s[i]) & 0xFF] ^ ((crc32val >> 8) & 0x00FFFFFF);
    }

    return labs(crc32val ^ 0xFFFFFFFF);
}
```

**Comment by 5ooo** [comment]
应该是因为32位机器和64位机器的long所占字节不一样导致的。
假设(crc32val ^ 0xFFFFFFFF)的值是4048690643，如果long占4个字节，labs返回值是246276653（也就是把4048690643当作-246276653了），如果long占8个字节，那么labs的返回值还是4048690643，这就导致不同机器计算出来的crc不一样，是补码关系了
解决：我这边是去掉最后的labs就可以了，计算都是用uint32_t的值，最后不用调用labs

**Comment by mygityf** [comment]
你的方法是对的。
